/********************************************************************
* LHEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error LHEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableLHEventDict();
extern void G__cpp_setup_inheritanceLHEventDict();
extern void G__cpp_setup_typetableLHEventDict();
extern void G__cpp_setup_memvarLHEventDict();
extern void G__cpp_setup_globalLHEventDict();
extern void G__cpp_setup_memfuncLHEventDict();
extern void G__cpp_setup_funcLHEventDict();
extern void G__set_cpp_environmentLHEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "LHEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LHEventDictLN_TClass;
extern G__linked_taginfo G__LHEventDictLN_TBuffer;
extern G__linked_taginfo G__LHEventDictLN_TMemberInspector;
extern G__linked_taginfo G__LHEventDictLN_TObject;
extern G__linked_taginfo G__LHEventDictLN_TString;
extern G__linked_taginfo G__LHEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__LHEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LHEventDictLN_TClonesArray;
extern G__linked_taginfo G__LHEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__LHEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LHEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__LHEventDictLN_LHEvent;
extern G__linked_taginfo G__LHEventDictLN_LHHit;
extern G__linked_taginfo G__LHEventDictLN_LHWave;

/* STUB derived class for protected member access */
