/********************************************************************
* LHRecEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error LHRecEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableLHRecEventDict();
extern void G__cpp_setup_inheritanceLHRecEventDict();
extern void G__cpp_setup_typetableLHRecEventDict();
extern void G__cpp_setup_memvarLHRecEventDict();
extern void G__cpp_setup_globalLHRecEventDict();
extern void G__cpp_setup_memfuncLHRecEventDict();
extern void G__cpp_setup_funcLHRecEventDict();
extern void G__set_cpp_environmentLHRecEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "LHRecEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LHRecEventDictLN_TClass;
extern G__linked_taginfo G__LHRecEventDictLN_TBuffer;
extern G__linked_taginfo G__LHRecEventDictLN_TMemberInspector;
extern G__linked_taginfo G__LHRecEventDictLN_TObject;
extern G__linked_taginfo G__LHRecEventDictLN_TString;
extern G__linked_taginfo G__LHRecEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__LHRecEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LHRecEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__LHRecEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LHRecEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__LHRecEventDictLN_LHRecEvent;

/* STUB derived class for protected member access */
